services:
  - type: web
    name: yakuphan-portfolio
    env: static
    buildCommand: npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
